supabase_url = "https://iinoadrmkhfitwykmvcp.supabase.co"
supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlpbm9hZHJta2hmaXR3eWttdmNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU1MzM1MjYsImV4cCI6MjA4MDg5MzUyNn0.lzaTKG7_lNS47l65p5jfAIE9krBBa9RTlPpGi5rmpoQ"
#supabase_url = "https://xxxx.supabase.co"
#supabase_key = "YOUR_SUPABASE_ANON_KEY"
